#!/bin/sh

# Define variables
time="/usr/bin/time"
workflow="/import/bc2/home/zavolan/kanitz/PROJECTS/SpliceFactorsReprogramming/frameworksAuxiliary/Anduril/run/kallistoIndexTest.and"
bundleDir="/import/bc2/home/zavolan/kanitz/PROJECTS/SpliceFactorsReprogramming/frameworksAuxiliary/Anduril/bundle"
execDir="/import/bc2/home/zavolan/kanitz/PROJECTS/SpliceFactorsReprogramming/frameworksAuxiliary/Anduril/testOut/kallistoIndex"
threads=1

# Execute Anduril
$time anduril run $workflow --bundle $bundleDir --execution-dir "${execDir}" --log "${execDir}/LOG" --threads $threads
